name: Bundle Visualizer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  viz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build with visualizer
        run: VIZ=1 npm run build
        env:
          CI: true

      - name: Upload visualizer artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/stats.html
